name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
   
    - name: Install and run cpplint
      run: pip install cpplint && cpplint --recursive --exclude=build .

    - name: Update apt-get
      run: sudo apt-get update

    - name: Install GCC
      run: sudo apt-get install -yq g++

    - name: Install CMake
      run: sudo apt-get install -yq cmake

    - name: Boost
      run: sudo apt-get install -yq libboost-program-options-dev

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all
      env:
        MAKEFLAGS: "-j3"

    - name: Tests
      working-directory: ${{github.workspace}}/build/tests
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure || true
